[build]
command = "npm install && npm run build"
publish = "dist"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.18.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200