[build]
command = "npm install --platform=linux --arch=x64 @esbuild/linux-x64 && npm install && npm run build"
publish = "dist"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200