[build]
command = "rm -rf node_modules package-lock.json && npm install && npm run build"
publish = "dist"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.18.0"

[[redirects]]
from = "/api/*"
to = "http://54.180.254.133:8080/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200