const ListDummyProjects = [
  {
    id: 1,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 2,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },
  {
    id: 3,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 4,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },
  {
    id: 5,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 6,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },
    {
    id: 7,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 8,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },  {
    id: 9,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 10,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },  {
    id: 11,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 12,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },  {
    id: 13,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 14,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },  {
    id: 15,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 16,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },  {
    id: 17,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    image: "/images/kwvizer.png",
  },
  {
    id: 18,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    image: "/images/kwlogo.png",
  },
];

export default ListDummyProjects;