const ListDummyProjects = [
  {
    id: 1,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30",
    generation: "12기",
    activity: "해커톤"
  },
  {
    id: 2,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개프로젝트부연설명한줄소개",
    thumbnail: "/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30",
    generation: "12기"
  },
  {
    id: 3,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30",
    generation: "12기"
  },
  {
    id: 4,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    generation: "13기",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 5,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    generation: "13기",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 6,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
    {
    id: 7,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 8,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },  {
    id: 9,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 10,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },  
  {
    id: 11,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 12,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },  {
    id: 13,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 14,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },  {
    id: 15,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 16,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },  {
    id: 17,
    title: "KW-VIZER",
    type: "APP",
    description: "학사정보 기반 AI 진로 상담 챗봇",
    thumbnail: "/public/images/project-img.png",
    image: "/images/kwvizer.png",
    images: [
    "/images/kwvizer1.png",
    "/images/kwvizer2.png",
    "/images/kwvizer3.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
  {
    id: 18,
    title: "알콩달콩",
    type: "WEB",
    description: "프로젝트부연설명한줄소개",
    thumbnail: "/public/images/project-img2.png",
    image: "/images/kwlogo.png",
    images: [
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwlogo.png",
    "/images/kwvizer4.png",
    ],
    team: [
      { role: "frontend", name: "고은빈" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
      { role: "frontend", name: "유승연" },
    ],
    stack: "React Django",
    term: "2024-09-01 ~ 2025-06-30"
  },
];

export default ListDummyProjects;